### ISSUE TITLE
Incorrect gene_model_pub_name name in Glycine/max/studies/glyma.Bai_Jing_2021.yml

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/gene-function-registry#38]
In Glycine/max/studies/glyma.Bai_Jing_2021.yml
the gene_model_pub_name is given as `Glyma.01g42420` but should be `Glyma01g42420` (without dot). See Supplementary Data File at https://www.sciencedirect.com/science/article/pii/S0168945219308404?via%3Dihub

Equivalent to glyma.Wm82.gnm2.ann1.Glyma.01G215100 - which is probably the better choice for gene_model_full_id

**Comment by ScottKalberer** [comment]
See my pull request to resolve this issue at "https://github.com/legumeinfo/gene-function-registry/pull/40" that presents the new and enhanced Bai_Jing_2020.yml.
