### ISSUE TITLE
Tutorial material 

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/gene-function-registry#61]
I am creating this issue to document some tutorial material that Ella has brought up.

- [ ] Screen recording of creating branches, making issues, creating and stopping a code space
- [ ] 'Cheat sheet' with the terminal and git commands

**Comment by ellatownsend90** [comment]
Thank you after I get through the first practice I can begin on making/ finding tutorials and cheat sheets

**Comment by jd-campbell** [comment]
moved to slack
